name: dagger-sample

on:
  pull_request:
    branches: [main]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Dagger do test
        uses: dagger/dagger-for-github@v3
        with:
          workdir: 
          version: 0.2
          cmds: |
            project update
            do lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Dagger do test
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do test