name: release-dev

on:
  workflow_run:
    workflows: ["ci-go"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Release
        uses: dagger/dagger-for-github@v3
        env:
          DAGGER_LOG_LEVEL: "debug"
          DAGGER_LOG_FORMAT: "plain"
          DAGGER_CACHE_TO: "type=gha,mode=max,scope=release-dev"
          DAGGER_CACHE_FROM: "type=gha,scope=release-dev"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          cmds: |
            project update
            do application api release remote
            do application cli release remote